In [1]:
from pyscarcopula.src.N2.N2Copula import N2Copula
from pyscarcopula.src.N7.N7Copula import N7Copula
from pyscarcopula.src.N8.N8Copula import N8Copula

from pyscarcopula.src.N22.N22Copula import N22Copula
from pyscarcopula.src.N21.N21Copula import N21Copula
from pyscarcopula.src.N20.N20Copula import N20Copula

from pyscarcopula.src.Gumbel.GumbelCopula  import GumbelCopula
from pyscarcopula.src.GenestGhoudi.GenestGhoudiCopula  import GenestGhoudiCopula
from pyscarcopula.src.GumbelBarnett.GumbelBarnettCopula  import GumbelBarnettCopula
from pyscarcopula.src.Frank.FrankCopula  import FrankCopula
from pyscarcopula.src.Joe.JoeCopula  import JoeCopula
from pyscarcopula.src.AliMikhailHaq.AliMikhailHaqCopula  import AliMikhailHaqCopula

from pyscarcopula.aux_functions.funcs import transform_pseudo_obs

import pandas as pd

Read data

In [17]:
'''Read data and transform returns to pseudo observations'''
returns_data1 = pd.read_csv(r"data/test_returns_data_for_eis.csv", index_col=0) # Data from MOEX for tickers: AFKS, ROSN, SBER, YNDX. 
                                                                                # Data starts from 01.01.2020 with 30-minutes interval  
pseudo_obs_data1 = transform_pseudo_obs(returns_data1.values[0:500])


returns_data2 = pd.read_csv(r"data/dj.csv", sep=';') # Daily data of indexies DowJones и NASDAQ. 
                                                     # Data starts from 01.01.1990
pseudo_obs_data2 = transform_pseudo_obs(returns_data2.values[0:500])

Available approximations methods

In [3]:
'''Copula could be approximated by calling method `fit`. 
Available methods:
1. MLE - maximum likelihood estimation
2. SCAR-M - efficient importance sampling (by default)
3. SCAR-P - Natural sampler 

Example of approximation for Joe copula.. The path which minimizer goes through is printed. 
Result of calculations - fun - value of log likelihood (for SCAR-P and M - average on number of trajectories `n_tr`);
x - set of regression parameters omega.

First run could lasts longer due to optimizations of numba python library (functions runs after compilation. Second runs starts immediately).
'''
joe_cop = JoeCopula(4)
joe_cop.fit(pseudo_obs_data1, n_tr = 200, m_iters = 5, method = 'SCAR-M', seed = 10)

  message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  success: True
   status: 0
      fun: 42.300816795915935
        x: [-2.055e-02  9.512e-01  2.023e-01]
      nit: 29
      jac: [-4.036e-04 -1.776e-05  3.944e-04]
     nfev: 180
     njev: 45
 hess_inv: <3x3 LbfgsInvHessProduct with dtype=float64>
     name: Joe copula
   method: SCAR-M

In [4]:
joe_cop.fit(pseudo_obs_data1, n_tr = 10000, method = 'SCAR-P', seed = 10)

  message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  success: True
   status: 0
      fun: 37.986403643540505
        x: [-9.834e-02  7.961e-01  1.780e-01]
      nit: 18
      jac: [-4.449e-01  3.028e-01  1.338e-01]
     nfev: 88
     njev: 22
 hess_inv: <3x3 LbfgsInvHessProduct with dtype=float64>
     name: Joe copula
   method: SCAR-P

In [5]:
'''MLE'''
joe_cop = JoeCopula(4)
joe_cop.fit(pseudo_obs_data1, method = 'MLE')

  message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  success: True
   status: 0
      fun: 33.12309757218025
        x: [ 1.143e+00]
      nit: 4
      jac: [ 1.057e-03]
     nfev: 10
     njev: 5
 hess_inv: <1x1 LbfgsInvHessProduct with dtype=float64>
     name: Joe copula
   method: MLE

Choose best copula. Dataset 1.

In [21]:
'''in progress'''

dim = 4
method = 'SCAR-M'
dataset = pseudo_obs_data1
cop_list = [
N2Copula(dim),
N7Copula(dim),
N8Copula(dim),
N22Copula(dim),
N21Copula(dim),
N20Copula(dim),
GumbelCopula(dim),
GenestGhoudiCopula(dim),
GumbelBarnettCopula(dim),
FrankCopula(dim),
JoeCopula(dim),
AliMikhailHaqCopula(dim)
]
cop_name = []
log_likelihood = []
x = []
success = []
for i in cop_list:
    res = i.fit(dataset, method = method)
    cop_name.append(i.name)
    log_likelihood.append(res.fun)
    x.append(res.x)
    success.append(res.success)
calc_data = {'copula name': cop_name, 'log likelihood': log_likelihood, 'x': x, 'success': success, 'method': method }
df = pd.DataFrame(data=calc_data)
df

c:\Users\3dgnom\Downloads\vs_Code_Sirius_Project\moex data\scar\pyscarcopula\src\ArchimedianCopula.py:295: RuntimeWarning: divide by zero encountered in log
  copula_log_data = np.sum(np.log(self.np_pdf()(data[t], self.transform(lambda_data[t]) )) )
c:\Users\3dgnom\Downloads\vs_Code_Sirius_Project\moex data\scar\pyscarcopula\src\ArchimedianCopula.py:295: RuntimeWarning: invalid value encountered in log
  copula_log_data = np.sum(np.log(self.np_pdf()(data[t], self.transform(lambda_data[t]) )) )
c:\Users\3dgnom\Downloads\vs_Code_Sirius_Project\moex data\scar\pyscarcopula\src\ArchimedianCopula.py:295: RuntimeWarning: invalid value encountered in log
  copula_log_data = np.sum(np.log(self.np_pdf()(data[t], self.transform(lambda_data[t]) )) )
c:\Users\3dgnom\Downloads\vs_Code_Sirius_Project\moex data\scar\pyscarcopula\src\ArchimedianCopula.py:295: RuntimeWarning: invalid value encountered in log
  copula_log_data = np.sum(np.log(self.np_pdf()(data[t], self.transform(lambda_data[t]) )) )
c:\Users\3dgnom\Downloads\vs_Code_Sirius_Project\moex data\scar\pyscarcopula\src\ArchimedianCopula.py:295: RuntimeWarning: divide by zero encountered in log
  copula_log_data = np.sum(np.log(self.np_pdf()(data[t], self.transform(lambda_data[t]) )) )
c:\Users\3dgnom\Downloads\vs_Code_Sirius_Project\moex data\scar\pyscarcopula\src\ArchimedianCopula.py:295: RuntimeWarning: invalid value encountered in log
  copula_log_data = np.sum(np.log(self.np_pdf()(data[t], self.transform(lambda_data[t]) )) )
c:\Users\3dgnom\Downloads\vs_Code_Sirius_Project\moex data\scar\pyscarcopula\src\ArchimedianCopula.py:295: RuntimeWarning: invalid value encountered in log
  copula_log_data = np.sum(np.log(self.np_pdf()(data[t], self.transform(lambda_data[t]) )) )
c:\Users\3dgnom\Downloads\vs_Code_Sirius_Project\moex data\scar\pyscarcopula\src\ArchimedianCopula.py:295: RuntimeWarning: divide by zero encountered in log
  copula_log_data = np.sum(np.log(self.np_pdf()(data[t], self.transform(lambda_data[t]) )) )
c:\Users\3dgnom\Downloads\vs_Code_Sirius_Project\moex data\scar\pyscarcopula\src\ArchimedianCopula.py:295: RuntimeWarning: invalid value encountered in log
  copula_log_data = np.sum(np.log(self.np_pdf()(data[t], self.transform(lambda_data[t]) )) )
c:\Users\3dgnom\Downloads\vs_Code_Sirius_Project\moex data\scar\pyscarcopula\src\ArchimedianCopula.py:295: RuntimeWarning: invalid value encountered in log
  copula_log_data = np.sum(np.log(self.np_pdf()(data[t], self.transform(lambda_data[t]) )) )

,copula name,log likelihood,x,success,method
0,N2 copula,-1.000000e+04,"[0.05, 0.95, 0.05]",True,SCAR-M
1,N7 copula,-9.681145e-14,"[-4.915043560388185e-09, 0.6013651180274746, -...",True,SCAR-M
2,N8 copula,-3.006488e+01,"[0.06641402640242709, 0.9801772529602608, 0.05...",True,SCAR-M
3,N22 copula,-1.000000e+04,"[0.05, 0.95, 0.05]",True,SCAR-M
4,N21 copula,-1.000000e+04,"[0.05, 0.95, 0.05]",True,SCAR-M
5,N20 copula,-1.000000e+04,"[0.05, 0.95, 0.05]",True,SCAR-M
6,Gumbel copula,5.470117e+01,"[-0.09333449573792059, 0.8091185125428954, 0.0...",True,SCAR-M
7,Genest-Ghoudi copula,-1.000000e+04,"[0.05, 0.95, 0.05]",True,SCAR-M
8,Gumbel-Barnett copula,-1.000000e+04,"[0.05, 0.95, 0.05]",True,SCAR-M
9,Frank copula,5.331454e+01,"[0.0324624604512421, 0.9758222755015933, 0.104...",True,SCAR-M
10,Joe copula,3.477246e+01,"[-0.14467843096869976, 0.741559992933329, 0.10...",True,SCAR-M
11,Ali-Mikhail-Haq copula,5.505778e+01,"[0.03302335652168274, 0.9439998028010012, 0.06...",True,SCAR-M

Choose best copula. Dataset 2.

In [20]:
dim = 2
method = 'SCAR-M'
dataset = pseudo_obs_data2
cop_list = [
N2Copula(dim),
N7Copula(dim),
N8Copula(dim),
N22Copula(dim),
N21Copula(dim),
N20Copula(dim),
GumbelCopula(dim),
GenestGhoudiCopula(dim),
GumbelBarnettCopula(dim),
FrankCopula(dim),
JoeCopula(dim),
AliMikhailHaqCopula(dim)
]
cop_name = []
log_likelihood = []
x = []
success = []
for i in cop_list:
    res = i.fit(dataset, method = method)
    cop_name.append(i.name)
    log_likelihood.append(res.fun)
    x.append(res.x)
    success.append(res.success)
calc_data = {'copula name': cop_name, 'log likelihood': log_likelihood, 'x': x, 'success': success, 'method': method }
df = pd.DataFrame(data=calc_data)
df

c:\Users\3dgnom\Downloads\vs_Code_Sirius_Project\moex data\scar\pyscarcopula\src\ArchimedianCopula.py:295: RuntimeWarning: invalid value encountered in log
  copula_log_data = np.sum(np.log(self.np_pdf()(data[t], self.transform(lambda_data[t]) )) )
c:\Users\3dgnom\Downloads\vs_Code_Sirius_Project\moex data\scar\pyscarcopula\src\ArchimedianCopula.py:295: RuntimeWarning: divide by zero encountered in log
  copula_log_data = np.sum(np.log(self.np_pdf()(data[t], self.transform(lambda_data[t]) )) )
c:\Users\3dgnom\Downloads\vs_Code_Sirius_Project\moex data\scar\pyscarcopula\src\ArchimedianCopula.py:295: RuntimeWarning: divide by zero encountered in log
  copula_log_data = np.sum(np.log(self.np_pdf()(data[t], self.transform(lambda_data[t]) )) )
c:\Users\3dgnom\Downloads\vs_Code_Sirius_Project\moex data\scar\pyscarcopula\src\ArchimedianCopula.py:295: RuntimeWarning: divide by zero encountered in log
  copula_log_data = np.sum(np.log(self.np_pdf()(data[t], self.transform(lambda_data[t]) )) )
c:\Users\3dgnom\Downloads\vs_Code_Sirius_Project\moex data\scar\pyscarcopula\src\ArchimedianCopula.py:295: RuntimeWarning: divide by zero encountered in log
  copula_log_data = np.sum(np.log(self.np_pdf()(data[t], self.transform(lambda_data[t]) )) )

,copula name,log likelihood,x,success,method
0,N2 copula,-1.000000e+04,"[0.05, 0.95, 0.05]",True,SCAR-M
1,N7 copula,-2.455813e-13,"[-4.205242103324998e-09, 0.600751385708967, -2...",True,SCAR-M
2,N8 copula,1.865323e+02,"[0.08814796301129453, 0.9969931975409346, 0.05...",True,SCAR-M
3,N22 copula,8.952524e+01,"[0.08127690405417498, 0.9391484569281667, 0.08...",True,SCAR-M
4,N21 copula,-1.000000e+04,"[0.05, 0.95, 0.05]",True,SCAR-M
5,N20 copula,-1.000000e+04,"[0.05, 0.95, 0.05]",True,SCAR-M
6,Gumbel copula,2.317618e+02,"[0.15922163463392613, 0.8927846153166415, 0.08...",True,SCAR-M
7,Genest-Ghoudi copula,-1.000000e+04,"[0.05, 0.95, 0.05]",True,SCAR-M
8,Gumbel-Barnett copula,1.360430e-02,"[0.06956369522422476, 0.9857858536805487, 0.04...",False,SCAR-M
9,Frank copula,2.174670e+02,"[0.08509800642212165, 0.9881814749205169, 0.05...",True,SCAR-M
10,Joe copula,1.709422e+02,"[0.05479361041492311, 0.9655876661535874, 0.06...",False,SCAR-M
11,Ali-Mikhail-Haq copula,1.865327e+02,"[0.07639076655231773, 0.9942261379509102, 0.05...",False,SCAR-M